version: "3"

services:
  proxy:
    image: nginx:alpine
    ports:
      - 8080:8080
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      quill_network:
        ipv4_address: 172.51.0.2

  node:
    image: node:latest
    volumes:
      - .:/app
    working_dir: /app
    command: yarn start
    networks:
      quill_network:
        ipv4_address: 172.51.0.3

  mongo:
    image: mongo:latest
    # we don't care about the data, docker-compose down will prune it instead
    networks:
      quill_network:
        ipv4_address: 172.51.0.4

  mongo_express:
    image: mongo-express:latest
    ports:
      - 8082:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_AUTH_DATABASE=quill
      - ME_CONFIG_MONGODB_AUTH_USERNAME=user
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=password
    networks:
      quill_network:
        ipv4_address: 172.51.0.5

  smtp:
    image: djfarrelly/maildev
    ports:
      - 8081:80
    networks:
      quill_network:
        ipv4_address: 172.51.0.6

networks:
  quill_network:
    ipam:
      config:
        - subnet: 172.51.0.0/24
