version: "3"

services:
  proxy:
    image: nginx:latest
    ports:
      - 8080:8080
    volumes:
      - ./docker/proxy.conf:/etc/nginx/conf.d/default.conf
    links:
      - node

  node:
    image: node:alpine
    volumes:
      - .:/app
    working_dir: /app
    command: yarn dev
    env_file:
      - ./docker/node.env
    links:
      - smtp
      - mongo
  
  mongo:
    image: mongo:latest
  
  mongo_express:
    image: mongo-express:latest
    ports:
      - 8082:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_AUTH_DATABASE=quill
      - ME_CONFIG_MONGODB_AUTH_USERNAME=user
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=password
    links:
      - mongo
  
  smtp:
    image: djfarrelly/maildev
    ports:
      - 8081:80
